language: julia
compiler:
  - clang
os:
  - linux
  - osx
julia:
  - release
  - nightly
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev libgmp-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.add("Devectorize")'
  - julia -e 'Pkg.add("Convex")'
  - julia -e 'Pkg.add("Mosek")'
  - julia -e 'Pkg.build("Mosek")'
  - julia -e 'Pkg.add("FactCheck")' 
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("DensestCommonSubgraph"); Pkg.test("DensestCommonSubgraph"; coverage=true)'
notifications:
  email: false

